spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/train"
    username: "root"
    password: "12345678"
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE